version: "3.8"

services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - 3000:80
    depends_on:
      - app

  ####### DEV ######
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./app:/app

  test:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./app:/app
    command: ["npm", "run", "test"]
  ####### PROD ##########
  # app:
  #   build:
  #     context: ./app
  #     dockerfile: Dockerfile
  #   volumes:
  #     - /app/node_modules
  #     - ./app:/app
